In [1]:
import numpy as np
import cv2 as cv

In [5]:
img = cv.imread("picture.jpg")

In [6]:
img

array([[[  0,  39,  49],
        [  0,  40,  50],
        [  0,  39,  52],
        ...,
        [ 43, 177, 154],
        [ 19, 165, 140],
        [  0, 144, 114]],

       [[  0,  40,  50],
        [  0,  38,  48],
        [  0,  38,  51],
        ...,
        [ 37, 173, 149],
        [ 15, 165, 136],
        [  0, 151, 120]],

       [[  0,  41,  49],
        [  0,  41,  49],
        [  0,  40,  50],
        ...,
        [ 25, 169, 140],
        [  0, 149, 116],
        [  0, 140, 106]],

       ...,

       [[ 95, 124, 138],
        [ 97, 126, 140],
        [ 95, 125, 136],
        ...,
        [ 64,  90, 104],
        [ 78, 104, 118],
        [ 89, 115, 129]],

       [[ 99, 126, 140],
        [ 98, 127, 141],
        [ 99, 128, 142],
        ...,
        [ 71,  97, 111],
        [ 80, 106, 120],
        [ 86, 112, 126]],

       [[104, 131, 145],
        [100, 127, 141],
        [100, 129, 143],
        ...,
        [ 76, 102, 116],
        [ 77, 103, 117],
        [ 78, 104, 118]]

In [7]:
cv.imshow("Original Image" ,img)
cv.waitKey(0)
cv.destroyAllWindows()

In [11]:
re_img = cv.resize(img,(700,600))

In [12]:
re_img

array([[[  0,  38,  50],
        [  0,  83,  76],
        [  0, 111,  91],
        ...,
        [132, 202, 215],
        [  0,  54,  46],
        [ 35, 168, 145]],

       [[  0,  43,  52],
        [  0,  79,  79],
        [  3, 116,  96],
        ...,
        [ 32, 125, 114],
        [  0,  73,  56],
        [ 16, 148, 127]],

       [[  0,  43,  51],
        [  0,  16,  19],
        [ 14, 124, 106],
        ...,
        [  6,  77,  59],
        [  1,  71,  56],
        [  0, 123,  94]],

       ...,

       [[ 96, 128, 139],
        [ 97, 129, 140],
        [ 68, 102, 115],
        ...,
        [ 62,  88, 102],
        [ 65,  88, 103],
        [ 74, 100, 114]],

       [[ 86, 118, 129],
        [ 92, 124, 135],
        [ 85, 117, 131],
        ...,
        [ 65,  91, 105],
        [ 71,  94, 109],
        [ 71,  97, 111]],

       [[ 97, 127, 141],
        [107, 143, 153],
        [102, 130, 144],
        ...,
        [ 59,  85,  99],
        [ 66,  89, 104],
        [ 69,  95, 109]]

In [13]:
cv.imwrite(r"D:\Data Science notes\AI\image Augmentation\resize_img.jpg",re_img)
cv.imshow("Resized Image" ,re_img)
cv.waitKey(0)
cv.destroyAllWindows()

In [14]:
red = re_img.copy()

In [15]:
red.shape

(600, 700, 3)

In [16]:
red[:,:,[0,1]]=0

In [23]:
cv.imwrite(r"D:\Data Science notes\AI\image Augmentation\redcolor_img.jpg",red)
cv.imshow("Red Image",red)
cv.waitKey(0)
cv.destroyAllWindows()

In [24]:
green = re_img.copy()

In [25]:
green[:,:,[0,2]]=0

In [28]:
cv.imwrite(r"D:\Data Science notes\AI\image Augmentation\green_img.jpg",green)
cv.imshow("green Image" ,green)
cv.waitKey(0)
cv.destroyAllWindows()

In [29]:
arr = np.random.randint(0, 255,36).reshape(3,4,3)

In [30]:
arr.shape

(3, 4, 3)

In [31]:
arr[:,:,[0,1]] =0
arr

array([[[  0,   0,  77],
        [  0,   0,  61],
        [  0,   0, 107],
        [  0,   0, 158]],

       [[  0,   0, 175],
        [  0,   0,  45],
        [  0,   0, 155],
        [  0,   0, 118]],

       [[  0,   0, 178],
        [  0,   0, 226],
        [  0,   0,  91],
        [  0,   0,  83]]], dtype=int32)

In [32]:
gray_img = cv.cvtColor(re_img ,cv.COLOR_BGR2GRAY)

In [33]:
cv.imwrite(r"D:\Data Science notes\AI\image Augmentation\gray_image.jpg",gray_img)
cv.imshow("Gray Image" ,gray_img)
cv.waitKey(0)
cv.destroyAllWindows()

In [34]:
blur_img1= cv.GaussianBlur(re_img ,(3,3),2) #(5,5)kernel should be always odd
blur_img2= cv.GaussianBlur(re_img ,(5,5),6)

In [35]:
two_img = np.hstack((blur_img1,blur_img2))

In [36]:
cv.imwrite(r"D:\Data Science notes\AI\image Augmentation\blur_imgs.jpg",two_img)
cv.imshow("Blur Images" ,two_img)
cv.waitKey(0)
cv.destroyAllWindows()

In [37]:
edges1 = cv.Canny(gray_img,100,200)
edges2 = cv.Canny(gray_img,150,300)

In [38]:
two_edges = np.hstack((edges1,edges2))

In [39]:
cv.imwrite(r"D:\Data Science notes\AI\image Augmentation\two_edges_imgs.jpg",two_edges)
cv.imshow("Edges of Images" ,two_edges)
cv.waitKey(0)
cv.destroyAllWindows()

In [40]:
flip_vert =cv.flip(re_img,0)
flip_hori =cv.flip(re_img,1)

In [41]:
two_flip = np.hstack((flip_vert,flip_hori))

In [43]:
cv.imwrite(r"D:\Data Science notes\AI\image Augmentation\flipped_imgs.jpg",two_flip)
cv.imshow("Rotated Image" ,two_flip)
cv.waitKey(0)
cv.destroyAllWindows()

In [47]:
angle =60
rows ,cols = re_img.shape[:2] # rows means widhts ,cols means height
center = (cols//2,rows//2)

In [68]:
shear_factor =0.10

In [69]:
shear_mat = np.float32([[1,shear_factor,0],[0,1,0]])

In [70]:
sheared_img = cv.warpAffine(re_img,shear_mat,(cols + int(shear_factor*rows),rows))

In [71]:
cv.imwrite(r"D:\Data Science notes\AI\image Augmentation\flipped_imgs.jpg",sheared_img)
cv.imshow("skewed Image" ,sheared_img)
cv.waitKey(0)
cv.destroyAllWindows()